import { Inter } from "next/font/google";
import "./globals.css";
import AuthGuard from "../pages/component/authguard"; // adjust path if needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bookie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthGuard />
        {children}
      </body>
    </html>
  );
}
